# Generated by Django 4.2.11 on 2026-06-16 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=20)),
                ('stream', models.CharField(choices=[('engineering', 'Engineering'), ('medical', 'Medical'), ('management', 'Management'), ('commerce', 'Commerce'), ('arts', 'Arts & Science'), ('law', 'Law'), ('design', 'Design'), ('pharmacy', 'Pharmacy'), ('nursing', 'Nursing')], max_length=20)),
                ('duration_years', models.DecimalField(decimal_places=1, max_digits=3)),
                ('eligibility', models.CharField(max_length=255)),
                ('avg_salary_min', models.IntegerField(default=0, help_text='In lakhs PA')),
                ('avg_salary_max', models.IntegerField(default=0, help_text='In lakhs PA')),
                ('description', models.TextField(blank=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-is_popular', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CareerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_opportunities', to='courses.course')),
            ],
            options={
                'db_table': 'career_opportunities',
            },
        ),
        migrations.CreateModel(
            name='CollegeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_per_year', models.IntegerField(default=0)),
                ('seats_available', models.IntegerField(default=0)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_courses', to='colleges.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_courses', to='courses.course')),
            ],
            options={
                'db_table': 'college_courses',
                'unique_together': {('college', 'course')},
            },
        ),
    ]
